# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb2cc3938ec7a20684f5e43e29a7e278cb0953bbb5f7ad2532f3a16fac5aca049be503eda7f3d76ac4882c2beebf6b3298dd698b392c322e0d25fb89461ed88

test:
  secret_key_base: ddaa2ee2a51425e0dee69a21b9382c854eca3b6f93f868a9010de88e5f9470a666844f7536fd843f915e6b3a7dfbf8e4f12e8147b200dae31862ec9f78b495e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
